LIVE_CAPTIONS_UUID_PREFIX = "live_captions"

MIMO_ASR_CHANNEL_ID = 22
MIMO_AUDIO_TOKENIZER_REPO = "XiaomiMiMo/MiMo-Audio-Tokenizer"
MIMO_ASR_MODELS = [
    "LeaderboardModel1/MiMo-V2.5-ASR-AutoRound-W4A16-RTN",
    "XiaomiMiMo/MiMo-V2.5-ASR",
]
DEFAULT_MIMO_ASR_MODEL = MIMO_ASR_MODELS[0]

NEMOTRON_ASR_CHANNEL_ID = 23
NEMOTRON_ASR_MODEL = "nvidia/nemotron-3.5-asr-streaming-0.6b"
NEMOTRON_ASR_MODELS = [NEMOTRON_ASR_MODEL]
DEFAULT_NEMOTRON_ATT_CONTEXT = [56, 6]
